---
- name: Install log rotation dependencies
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - zstd
      - "cron{% if ansible_os_family == 'RedHat' %}ie{% endif %}"
      - logrotate

- name: Enable cron daemon
  systemd:
    name: "cron{% if ansible_os_family == 'RedHat' %}d{% endif %}.service"
    state: started
    enabled: true
  register: installed_logrotate_deps
