---
- name: Enable log rotation
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ name }}"
    owner: root
    group: root
    mode: '0644'
#  notify: Restart cron service # TODO this isn't needed?
